apiVersion: v1
kind: PersistentVolume
metadata:
  name: hb-hotel-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/hb-hotel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hb-hotel-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi