services:
  hotel-booking-mysql:
    container_name: hotel-booking-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/data/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./hotel/src/main/java/dlim2012/hotel/entity/locality/countries.csv:/docker-entrypoint-initdb.d/countries.csv
    ports:
      - "9100:3306"
    restart: unless-stopped
    networks:
      - spring

  hotel-booking-zipkin:
    image: openzipkin/zipkin
    container_name: hotel-booking-zipkin
    ports:
      - "9201:9411"
    networks:
      - spring

#  hotel-booking-eureka-server:
#    image: dlim2012/tiny-url.eureka-server:latest
#    container_name: hotel-booking-eureka-server
#    ports:
#      - "9202:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - hotel-booking-zipkin

  hotel-booking-zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: hotel-booking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  hotel-booking-broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: hotel-booking-broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - hotel-booking-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'hotel-booking-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.20:9092,PLAINTEXT_INTERNAL://hotel-booking-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9101:9200"
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - "9203:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  spring:
    driver: bridge
  elastic:
    name: elastic
    driver: bridge

volumes:
  mysql:
  es_data:
    driver: local