server:
  port:
    9005

spring:
  application:
    name: booking-management
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  data:
    cassandra:
      port: 9042
      contact-points: hb-cassandra.default.svc.cluster.local
      local-datacenter: datacenter1
      keyspace-name: mykeyspace
      schema-action: CREATE_IF_NOT_EXISTS
#      entity-base-package: com.dlim2012.archival.entity.cassandra

#  zipkin:
#    base-url: http://hb-zipkin:9411

  cache:
    type: redis
    cache-names:
      - hotel-booking
      - user-booking
      - booking-room
      - hotel
    redis:
      time-to-live: 10000
      cache-null-values: true

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    enabled: false

custom:
  security:
    rsa:
      public-key: classpath:certs/public.pem
    roles:
      - ADMIN
      - HOTEL_MANAGER
      - APP_USER
  redis:
    host: redis
    port: 6379
#  gateway: "http://10.0.0.110:8001"