server:
  port: 9008

spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: junghoonlim12@gmail.com
    password: kifzgmuzelkezkgj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: 10.0.0.110:9092

  zipkin:
    base-url: http://10.0.0.110:9201


eureka:
  instance:
    hostname: 10.0.0.110
    port: 9202
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
