server:
  port: 9000

spring:
  application:
    name: apigw
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "**"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      httpclient:
        ssl:
          useInsecureTrustManager: true
        routes:
          - id: user
            uri: lb://USER
            predicates:
              - Path=/api/v1/user/**
          - id: booking
            uri: lb://BOOKING
            predicates:
              - Path=/api/v1/booking/**
          - id: booking-management
            uri: lb://BOOKING-MANAGEMENT
            predicates:
              - Path=/api/v1/booking-management/**
          - id: hotel
            uri: lb://HOTEL
            predicates:
              - Path=/api/v1/hotel/**
          - id: search
            uri: lb://SEARC
            predicates:
              - Path=/api/v1/search/**



  zipkin:
    base-url: http://192.168.1.20:9201

eureka:
  instance:
    hostname: 192.168.1.20
    port: 9202
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
