server:
  port: 9000

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application:
    name: apigw
  banner:
    location: classpath:banner.txt
  cloud:
    discovery:
      locator:
        enabled: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "**"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/**
        - id: booking
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/booking/**
        - id: booking-management
          uri: lb://BOOKING-MANAGEMENT
          predicates:
            - Path=/api/v1/booking-management/**
        - id: hotel
          uri: lb://HOTEL
          predicates:
            - Path=/api/v1/hotel/**
        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/api/v1/search/**
        - id: search-consumer # for testing
          uri: lb://SEARCH-CONSUMER
          predicates:
            - Path=/api/v1/search-consumer/**
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

  zipkin:
    base-url: http://10.0.0.110:9201

eureka:
  instance:
    hostname: localhost
    port: 9200
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    registry-fetch-interval-seconds: 3