
server:
  port:
    9004

spring:
  application:
    name: archival
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hb-mysql-booking:3306/booking # ?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  data:
    cassandra:
      host:
      port: 9042
      contact-points: hb-cassandra
      local-datacenter: datacenter1
      keyspace-name: mykeyspace
      schema-action: CREATE_IF_NOT_EXISTS
      entity-base-package: com.dlim2012.archival.entity.cassandra

  zipkin:
    base-url: http://hb-zipkin:9411

  kafka:
    bootstrap-servers: http://hb-broker:9092

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
