server:
  port: 9001

spring:
  application:
    name: hotel
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.110:9100/hotel
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  zipkin:
    base-url: http://10.0.0.110:9201

  kafka:
    bootstrap-servers: 10.0.0.110:9092

eureka:
  instance:
    hostname: 10.0.0.110
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


logging:
  level:
    org:
      springframework:
        security: DEBUG

custom:
  security:
    rsa:
      public-key: classpath:certs/public.pem
    roles:
      - ADMIN
      - APP_USER
      - HOTEL_MANAGER
  file:
    path: "/Users/imjeonghun/IdeaProjects/hotelbooking/hotel/data"
    imageUrlPrefix: "http://10.0.0.110:9000/api/v1/hotel/image"