server:
  port: 9000

spring:
  application:
    name: hotel
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.20:9100/hotel
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  zipkin:
    base-url: http://192.168.1.20:9201

  kafka:
    bootstrap-servers: 192.168.1.20:9092

eureka:
  instance:
    hostname: 192.168.1.20
    port: 9202
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

file:
  path: "/Users/imjeonghun/IdeaProjects/hotelbooking/hotel/data"