package com.dlim2012.clients.entity;


public enum BookingStatus {
    RESERVED,
    RESERVED_FOR_TIMEOUT,
    BOOKED,
    CANCELLED_PAYMENT, // payment cancelled
    CANCELLED_PAYMENT_TIME_EXPIRED,
    CANCELLED_NO_PREPAYMENT,
    CANCELLED_BY_APP_USER,
    CANCELLED_BY_HOTEL_MANAGER,
    CANCELLED_BY_ADMIN,
    COMPLETED
}
