apiVersion: apps/v1
kind: Deployment
metadata:
  name: hb-user
  labels:
    app: hb-user
spec:
  replicas: 1
  template:
    metadata:
      name: hb-user
      labels:
        app: hb-user
    spec:
      containers:
        - name: hb-user
          image: dlim2012/hb.user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: DB_HOST
              value: hb-mysql-user
            - name: DB_NAME
              value: user
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password
      restartPolicy: Always
  selector:
    matchLabels:
      app: hb-user