server:
  port:
    9007

spring:
  zipkin:
    base-url: http://192.168.1.20:9201

eureka:
  instance:
    hostname: 192.168.1.20
    port: 9202
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


custom:
  elasticsearch:
    server: 192.168.1.20:9103
  security:
    rsa:
      public-key: classpath:certs/public.pem
    roles:
      - ADMIN
      - APP_USER