server:
  port:
    9002

spring:
  zipkin:
    base-url: http://192.168.1.20:9201

eureka:
  instance:
    hostname: 192.168.1.20
    port: 9202
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

