server:
  port:
    9007

spring:
  application:
    name: search
  banner:
    location: classpath:banner.txt
#  zipkin:
#    base-url: http://hb-zipkin:9411

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    enabled: false

custom:
  elasticsearch:
    host: hb-elasticsearch-es-http
    port: 9200
    username: elastic
    password: changeme
    useSsl: true
  security:
    rsa:
      public-key: classpath:certs/public.pem
    roles:
      - ADMIN
      - APP_USER